CREATE TABLE dbo.UPI_EOD
(
    UPI varchar(15) constraint UPI_EOD_PK primary key,
	AssetClass varchar(20),
	CFIDeliveryType varchar(100),
	CFIOptionStyleandType varchar(100),
	ClassificationType varchar(100),
	DeliveryType varchar(100),
	InstrumentType varchar(255),
	LastUpdateDateTime DATETIME2,
	Level varchar(100),
	NotionalCurrency varchar(5),
	NotionalSchedule varchar(100),
	OptionExerciseStyle varchar(255),
	OptionType varchar(100),
	OtherLegReferenceRate varchar(100),
	OtherLegReferenceRateTermUnit varchar(5),
	OtherLegReferenceRateTermValue varchar(100),
	OtherLegUnderlierCharacteristic varchar(100),
	OtherNotionalCurrency varchar(5),
	PlaceofSettlement varchar(255),
	Product varchar(100),
	ReferenceRate varchar(100),
	ReferenceRateTermUnit varchar(5),
	ReferenceRateTermValue varchar(100),
	ReturnorPayoutTrigger varchar(255),
	SettlementCurrency varchar(5),
	ShortName varchar(255),
	SingleorMultiCurrency varchar(100),
	Status varchar(20),
	StatusReason varchar(255),
	UnderlierName varchar(255),
	UnderlyingAssetType varchar(100),
	UnderlyingInstrumentIndex varchar(100),
	UnderlyingInstrumentIndexTermUnit varchar(5),
	UnderlyingInstrumentIndexTermValue varchar(100),
	ValuationMethodorTrigger varchar(100)
    StartTime datetime2 GENERATED ALWAYS AS ROW START HIDDEN,
    EndTime   datetime2 GENERATED ALWAYS AS ROW END HIDDEN,
    PERIOD FOR SYSTEM_TIME (StartTime, EndTime)
)WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.UPI_EOD_HISTORY));